export const metadata = { title: "Primer · Watchlist" };

// The primer is a self-contained, audited static document (generated by
// build_primer.py to web/public/primer.html, with a Technology / Healthcare /
// Frontier toggle). It is embedded verbatim via an iframe so the approved
// content has a single source of truth and never drifts. The same file is also
// shareable directly at /primer.html.
export default function Primer() {
  return (
    <main className="flex-1 min-h-[calc(100dvh-48px)] bg-zinc-950">
      <iframe
        src="/primer.html?theme=app"
        title="Field guide — Technology, Healthcare & Frontier"
        className="block h-full min-h-[calc(100dvh-48px)] w-full border-0"
      />
    </main>
  );
}
